---

name: Platform IO Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_call:

jobs:

  PlatformIO_Check:
    name: PlatformIO Check
    runs-on: ubuntu-latest
    steps:
      - name: Install PlatformIO Core
        run: |
          sudo apt install platformio -y
          pip install --upgrade platformio
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: PlatformIO Check
        run: pio check --fail-on-defect low
