name: Static Analysis

on: [push]

jobs:
  Source_Code_Static_Analysis:
    name: C++ Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      
      - name: PlatformIO Static Analysis
        run: pio check --fail-on-defect high

  Markdown_Lint_Check:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run markdownlint
        run: markdownlint '**/*.md'

  PlatformIO_Check:
    name: PlatformIO Check
    runs-on: ubuntu-latest
    steps:
      - name: Install PlatformIO Core
        run: |
          sudo apt install platformio -y
          pip install --upgrade platformio
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: PlatformIO Check
        run: pio check --fail-on-defect medium