name: Static Analysis

on: [push]

jobs:
# Commenting out Shell Check as no shell scripts in this repo
#   Shell_Check:
#     name: Shell Check
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Install Dependencies
#       run: sudo apt-get install -y shellcheck
#     - name: Shell Check
#       run: |
#         echo "Checking shell scripts"
#         shellcheck **/*.sh

  Markdown_Lint_Check:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run markdownlint
        run: markdownlint '**/*.md'